[package]
name = "ragam_offline_reg"
version = "0.1.0"
authors = ["Farzeen"]
edition = "2018"

[dependencies.gtk]
version = "0.6"
features = ["v3_22"]

[dependencies.glib]
version = "0.7"

[dependencies.gdk]
version = "0.10"

[dependencies.fuzzy-filter]
version = "0.1"